# Generated by Django 4.2.5 on 2023-09-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker_palindromo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='id',
        ),
        migrations.AlterField(
            model_name='words',
            name='descrip',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
