# Generated by Django 4.2.5 on 2023-09-20 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checker_palindromo', '0002_remove_words_id_alter_words_descrip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='is_palindrome',
        ),
    ]
